name = "front-js-gcp"
compatibility_date = "2024-01-01"

# Custom domain
routes = [
  { pattern = "mtama-front.mtamaramu.com", custom_domain = true }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Production environment variables are set in Cloudflare dashboard
